### ISSUE TITLE
No result from Card.io Activity

### ISSUE THREAD

**Issue by JohanSnygg** [procedurallygenerated/flutter_card_io#4]
Has anyone got this working on Android API 25 and higher? I don't get the result from the Card.io activity.
Any ideas?
Thanks

**Comment by OttoChamo** [comment]
Did you solve it?

**Comment by JohanSnygg** [comment]
Yeah, use this one instead:
https://pub.dev/packages/flutter_paycards
It works great for me

**Comment by OttoChamo** [comment]
Thank you mate c:
